/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog.view;

import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Map;
import org.jpl7.Query;
import org.jpl7.Term;
import org.jpl7.Variable;

/**
 *
 * @author Michel
 */
public class Cliente extends javax.swing.JFrame {

    private ArrayList<HotelList> listHoteis;

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        jMenuBarTopo.setVisible(false);
        jPanelUserSelHotel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelSelCliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonLogar = new javax.swing.JButton();
        labelMesgErro = new java.awt.Label();
        jPanelUserSelHotel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaHoteis = new javax.swing.JTable();
        jMenuBarTopo = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemFazerReserva = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas de Reservas :: Login");
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE RESERVAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 70, 510, 60);

        jPanelSelCliente.setBackground(new java.awt.Color(204, 255, 204));
        jPanelSelCliente.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Login :");
        jPanelSelCliente.add(jLabel2);
        jLabel2.setBounds(130, 50, 65, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Senha :");
        jPanelSelCliente.add(jLabel3);
        jLabel3.setBounds(130, 90, 65, 30);

        jTextFieldLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });
        jPanelSelCliente.add(jTextFieldLogin);
        jTextFieldLogin.setBounds(220, 50, 210, 30);
        jPanelSelCliente.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(220, 90, 210, 30);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelSelCliente.add(jButtonCancelar);
        jButtonCancelar.setBounds(280, 170, 143, 40);

        jButtonLogar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLogar.setText("Logar");
        jButtonLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogarActionPerformed(evt);
            }
        });
        jPanelSelCliente.add(jButtonLogar);
        jButtonLogar.setBounds(110, 170, 143, 40);

        labelMesgErro.setAlignment(java.awt.Label.CENTER);
        labelMesgErro.setBackground(new java.awt.Color(204, 255, 204));
        labelMesgErro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelMesgErro.setForeground(new java.awt.Color(255, 0, 0));
        jPanelSelCliente.add(labelMesgErro);
        labelMesgErro.setBounds(130, 130, 300, 23);

        getContentPane().add(jPanelSelCliente);
        jPanelSelCliente.setBounds(120, 200, 530, 270);

        jPanelUserSelHotel.setBackground(new java.awt.Color(204, 255, 204));
        jPanelUserSelHotel.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Lista de Hotéis");
        jPanelUserSelHotel.add(jLabel4);
        jLabel4.setBounds(210, 20, 300, 70);

        jTableListaHoteis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        //LISTA OS HOTEIS
        jScrollPane1.setViewportView(jTableListaHoteis);

        jPanelUserSelHotel.add(jScrollPane1);
        jScrollPane1.setBounds(80, 90, 550, 160);

        getContentPane().add(jPanelUserSelHotel);
        jPanelUserSelHotel.setBounds(50, 170, 690, 270);

        jMenu1.setText("Reservas");

        jMenuItemFazerReserva.setText("Fazer");
        jMenuItemFazerReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFazerReservaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFazerReserva);
        jMenuItemFazerReserva.getAccessibleContext().setAccessibleParent(jMenu1);

        jMenuBarTopo.add(jMenu1);

        jMenu2.setText("Contas");
        jMenuBarTopo.add(jMenu2);

        jMenu3.setText("Sair");
        jMenuBarTopo.add(jMenu3);

        setJMenuBar(jMenuBarTopo);

        setBounds(0, 0, 808, 554);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogarActionPerformed
        // TODO add your handling code here:
        String nomeUser = this.buscaCliente(jTextFieldLogin.getText(), new String(jPasswordFieldSenha.getPassword()));
        if (nomeUser.equals("")) {
            labelMesgErro.setText("Usuário Inválido");
        } else {
            jPanelSelCliente.setVisible(false);
            jMenuBarTopo.setVisible(true);
        }

    }//GEN-LAST:event_jButtonLogarActionPerformed

    private void jMenuItemFazerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFazerReservaActionPerformed
        // TODO add your handling code here:
        jPanelUserSelHotel.setVisible(true);
        
        this.listHoteis = listaHoteis();
        System.out.println(this.listHoteis);
        HoteisTable model = new HoteisTable(this.listHoteis);
        jTableListaHoteis.setModel(model);
        
       
    }//GEN-LAST:event_jMenuItemFazerReservaActionPerformed

    private String buscaCliente(String login, String senha) {

        this.conexaoProlog();

        String questao = "buscaCliente(" + login + "," + senha + ",X)";

        Map<String, Term>[] solutions = Query.allSolutions(questao);

        String nCliente;

        if (solutions.length > 0) {
            nCliente = solutions[0].get("X").toString();
            return nCliente;
        }

        return "";
    }

    private void conexaoProlog() {
        String c = "consult('hoteis.pl')";
        if (!Query.hasSolution(c)) {
            System.out.println(c + "Falhou");
        }
    }

    public ArrayList<HotelList> listaHoteis() {
        this.conexaoProlog();

        Variable NOME = new Variable("NOME");
        Variable ENDERECO = new Variable("ENDERECO");
        Variable TELEFONE = new Variable("TELEFONE");
        Variable ESTRELAS = new Variable("ESTRELAS");
        Variable ESTACAO = new Variable("ESTACAO");
        Variable X = new Variable("_");

        Query qHotel = new Query("hotel", new Term[]{X, NOME, ENDERECO, TELEFONE, ESTRELAS, ESTACAO});

        Map<String, Term>[] solutions = qHotel.allSolutions();

        ArrayList<HotelList> nHoteis = new ArrayList<HotelList>();

        for (Map<String, Term> solution : solutions) {
            nHoteis.add(new HotelList(
                    solution.get("NOME").toString(),
                    solution.get("ENDERECO").toString(),
                    solution.get("TELEFONE").toString(),
                    solution.get("ESTRELAS").toString(),
                    solution.get("ESTACAO").toString()
            ));
        }
        return nHoteis;
    }

    public Integer listaSuiteDisponivel(String hotel) {

        String questao = "suites_disponiveis(X ," + hotel + ")";

        Map<String, Term>[] solutions = Query.allSolutions(questao);

        if (solutions.length > 0) {
            return solutions.length;
        }
        return 0;
    }

    public ArrayList<HotelList> getListHoteis() {
        return listHoteis;
    }

    public void setListHoteis(ArrayList<HotelList> listHoteis) {
        this.listHoteis = listHoteis;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBarTopo;
    private javax.swing.JMenuItem jMenuItemFazerReserva;
    private javax.swing.JPanel jPanelSelCliente;
    private javax.swing.JPanel jPanelUserSelHotel;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaHoteis;
    private javax.swing.JTextField jTextFieldLogin;
    private java.awt.Label labelMesgErro;
    // End of variables declaration//GEN-END:variables
}
