/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog.view;

import java.awt.HeadlessException;
import java.util.Map;
import javax.swing.*;
import org.jpl7.Atom;
import org.jpl7.PrologException;
import org.jpl7.Query;
import org.jpl7.Term;
import org.jpl7.Variable;

/**
 *
 * @author Michel
 */
public class Hotel extends JFrame {

    private String nomeHotel;

    /**
     * Creates new form NewJFrame
     */
    public Hotel() {
        initComponents();
        jPanelReservas.setVisible(false);
       
    }

    
    public void recebDados(Hotel model) {
        jLabelTitulo.setText("Gerenciar : " + model.getNomeHotel().toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelReservas = new javax.swing.JPanel();
        jComboBoxDataReserva = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Reservas");

        jLabel1.setBackground(new java.awt.Color(204, 255, 51));

        jLabelTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 51, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanelReservas.setBackground(new java.awt.Color(255, 255, 51));
        jPanelReservas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanelReservas.setLayout(null);

        jComboBoxDataReserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxDataReserva.setModel(new javax.swing.DefaultComboBoxModel(this.listaReserva("othon")));
        jComboBoxDataReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDataReservaActionPerformed(evt);
            }
        });
        jPanelReservas.add(jComboBoxDataReserva);
        jComboBoxDataReserva.setBounds(290, 130, 140, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Escolha um dia:");
        jPanelReservas.add(jLabel2);
        jLabel2.setBounds(130, 130, 160, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelReservas.add(jButton1);
        jButton1.setBounds(210, 190, 120, 23);

        jMenu1.setText("Reservas");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quartos");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Checkin");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Checkout");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Espera");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Sair");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(334, 334, 334)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        jPanelReservas.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jComboBoxDataReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDataReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDataReservaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public String[] listaHoteis() {

        this.conexaoProlog();

        Variable X = new Variable("X");
        Variable Z = new Variable("_");
        Query qHotel = new Query("hotel", new Term[]{Z, X, Z,Z,Z,Z});

        Map<String, Term>[] solutions = qHotel.allSolutions();

        String[] nHoteis = new String[10];

        nHoteis[0] = "-- SELECIONE --";
        for (int i = 0; i < solutions.length; i++) {
            nHoteis[i + 1] = solutions[i].get("X").toString();
        }

        return nHoteis;
    }

    public String[] listaReserva(String hotel) {
        //this.conexaoProlog();
        Variable X = new Variable("X");
        Variable Z = new Variable("_");

        String[] dataReserva = {""};
        
        try {
            Query qReserva = new Query("reserva", new Term[]{Z, X, Z, Z});

            Map<String, Term>[] solutions = qReserva.allSolutions();

             dataReserva = new String[10];
         
            for (int i = 0; i < solutions.length; i++) {
            dataReserva[i] = solutions[i].get("X").toString().replace("\'", "");
        }
        } catch (PrologException pl) {
            System.out.println(pl.getMessage());
        }
        
        System.out.println("Hotel " + hotel);

        return dataReserva;

    }

    private void conexaoProlog() {
        String c = "consult('hoteis.pl')";
        if (!Query.hasSolution(c)) {
            System.out.println(c + "Falhou");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxDataReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelReservas;
    // End of variables declaration//GEN-END:variables

    public String getNomeHotel() {
        return nomeHotel;
    }

    public void setNomeHotel(String nomeHotel) {
        this.nomeHotel = nomeHotel;
    }

}
