/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog.view;

import java.util.Arrays;
import org.jpl7.Query;
import org.jpl7.Term;
import org.jpl7.Variable;
import java.util.Map;
import javax.swing.JOptionPane;
//import prolog.model.Hotel;

/**
 *
 * @author Michel
 */
public class Menu extends javax.swing.JFrame {

    /**
     *
     */
    private Hotel objHotel;
    private String[] listHo;

    /**
     * Creates new form CadastroHotel
     */
    public Menu() {
        initComponents();
        jDesktopPaneSelHotel.setVisible(false);
        jInternalFrameSelHotel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelSelUser = new javax.swing.JPanel();
        jButtonCandastro = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonCancelar1 = new javax.swing.JButton();
        jDesktopPaneSelHotel = new javax.swing.JDesktopPane();
        jInternalFrameSelHotel = new javax.swing.JInternalFrame();
        jPanelSelHotel = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jComboBoxNomeHotel = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel5.setText("Estado");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Reservas");
        setName("framePrincipal"); // NOI18N

        jPanel1.setLayout(null);

        jPanelSelUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jButtonCandastro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCandastro.setText("Hotel");
        jButtonCandastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCandastroActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cliente");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonCancelar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar1.setText("Agência");

        javax.swing.GroupLayout jPanelSelUserLayout = new javax.swing.GroupLayout(jPanelSelUser);
        jPanelSelUser.setLayout(jPanelSelUserLayout);
        jPanelSelUserLayout.setHorizontalGroup(
            jPanelSelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelUserLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButtonCandastro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButtonCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanelSelUserLayout.setVerticalGroup(
            jPanelSelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSelUserLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanelSelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCandastro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        jPanel1.add(jPanelSelUser);
        jPanelSelUser.setBounds(20, 80, 550, 230);
        jPanelSelUser.getAccessibleContext().setAccessibleName("Menu");

        jDesktopPaneSelHotel.setBackground(new java.awt.Color(240, 240, 240));

        jInternalFrameSelHotel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.orange));
        jInternalFrameSelHotel.setTitle("Seleção de Hotel");
        jInternalFrameSelHotel.setVisible(true);

        jPanelSelHotel.setLayout(null);

        label2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label2.setText("Selecione um Hotel");
        jPanelSelHotel.add(label2);
        label2.setBounds(150, 50, 220, 30);

        jComboBoxNomeHotel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        //INSTACIA OBJETO HOTEL E LISTA
        this.objHotel = new Hotel();
        this.listHo  =  this.objHotel.listaHoteis();
        jComboBoxNomeHotel.setModel(new javax.swing.DefaultComboBoxModel(this.listHo));
        jComboBoxNomeHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNomeHotelActionPerformed(evt);
            }
        });
        jPanelSelHotel.add(jComboBoxNomeHotel);
        jComboBoxNomeHotel.setBounds(190, 100, 140, 21);

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelSelHotel.add(jButton1);
        jButton1.setBounds(160, 150, 90, 23);

        jButton2.setText("Cancelar");
        jPanelSelHotel.add(jButton2);
        jButton2.setBounds(280, 150, 90, 23);

        javax.swing.GroupLayout jInternalFrameSelHotelLayout = new javax.swing.GroupLayout(jInternalFrameSelHotel.getContentPane());
        jInternalFrameSelHotel.getContentPane().setLayout(jInternalFrameSelHotelLayout);
        jInternalFrameSelHotelLayout.setHorizontalGroup(
            jInternalFrameSelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSelHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        jInternalFrameSelHotelLayout.setVerticalGroup(
            jInternalFrameSelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameSelHotelLayout.createSequentialGroup()
                .addComponent(jPanelSelHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDesktopPaneSelHotelLayout = new javax.swing.GroupLayout(jDesktopPaneSelHotel);
        jDesktopPaneSelHotel.setLayout(jDesktopPaneSelHotelLayout);
        jDesktopPaneSelHotelLayout.setHorizontalGroup(
            jDesktopPaneSelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneSelHotelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrameSelHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jDesktopPaneSelHotelLayout.setVerticalGroup(
            jDesktopPaneSelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneSelHotelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jInternalFrameSelHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jDesktopPaneSelHotel.setLayer(jInternalFrameSelHotel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jDesktopPaneSelHotel);
        jDesktopPaneSelHotel.setBounds(0, 0, 580, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        setBounds(0, 0, 600, 385);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCandastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCandastroActionPerformed
        // TODO add your handling code here:
        jPanelSelUser.setVisible(false);
        jDesktopPaneSelHotel.setVisible(true);
        jInternalFrameSelHotel.setVisible(true);
    }//GEN-LAST:event_jButtonCandastroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Hotel model  = new Hotel();
        model.setNomeHotel(jComboBoxNomeHotel.getSelectedItem().toString());
        model.recebDados(model);
        model.setVisible(true);
        jDesktopPaneSelHotel.setVisible(false);
        jInternalFrameSelHotel.setVisible(false);
        jPanelSelUser.setVisible(false);
        jPanelSelHotel.setVisible(false);
        jPanel1.setVisible(false);

    // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxNomeHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNomeHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNomeHotelActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
         jDesktopPaneSelHotel.setVisible(false);
        jInternalFrameSelHotel.setVisible(false);
        jPanelSelUser.setVisible(false);
        jPanelSelHotel.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonCandastro;
    private javax.swing.JComboBox jComboBoxNomeHotel;
    private javax.swing.JDesktopPane jDesktopPaneSelHotel;
    private javax.swing.JInternalFrame jInternalFrameSelHotel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSelHotel;
    private javax.swing.JPanel jPanelSelUser;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables

    public String[] getListHo() {
        return listHo;
    }

    public void setListHo(String[] listHo) {
        this.listHo = listHo;
    }

    public Hotel getObjHotel() {
        return objHotel;
    }

    public void setObjHotel(Hotel objHotel) {
        this.objHotel = objHotel;
    }

}
